const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export { ADD_TO_CART, REMOVE_FROM_CART, CLEAR_CART, DECREASE_QUANTITY };
